---
- name: Set DNS server
  copy:
    content: "nameserver 8.8.8.8\n"
    dest: /etc/resolv.conf
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install MariaDB
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present

- name: Start and enable MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: true

- name: Create database
  mysql_db:
    name: notes
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create database user
  mysql_user:
    name: mywebapp
    password: "mywebapp_password"
    priv: "notes.*:ALL"
    host: "{{ hostvars[groups['workers'][0]]['ansible_host'] }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Configure MariaDB to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mariadb