#cloud-config
users:
  - name: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ansible_public_key}
  - name: teacher
    sudo: ALL=(ALL) ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$XORDFnuQ4V90B3WZ$VgPnXtd/3I..v.nZ9cpaWGD6UufkBdhSy3bW5teNiGg3jL7fdiHuUu0dTFdtnC4iVmM6B2TAdHGkKKK3.watR."
  - name: operator
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$XORDFnuQ4V90B3WZ$VgPnXtd/3I..v.nZ9cpaWGD6UufkBdhSy3bW5teNiGg3jL7fdiHuUu0dTFdtnC4iVmM6B2TAdHGkKKK3.watR."
  - name: app
    shell: /bin/false
    system: true

package_update: true
packages:
  - python3
  - python3-pip

runcmd:
  - echo "nameserver 8.8.8.8" > /etc/resolv.conf

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false

resize_rootfs: true
