[workers]
worker ansible_host=192.168.100.178

[db]
db ansible_host=192.168.100.34

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/ansible_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
